"""Add status column to Patient table

Revision ID: 92c9e2589a75
Revises: 442211e01040
Create Date: 2024-08-31 20:36:14.709157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c9e2589a75'
down_revision = '442211e01040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        # 添加 status 列，设置默认值为 '未就诊'
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, server_default='未就诊'))
        # 确保 doctor_id 列的外键约束
        batch_op.create_foreign_key('fk_patients_doctor_id', 'users', ['doctor_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')

    op.create_table('_alembic_tmp_patients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('medical_history', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('created', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='fk_patients_doctor_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
