"""Updated Diagnosis model

Revision ID: e21c1abf8654
Revises: 514546e89a5e
Create Date: 2024-09-12 13:56:45.025764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21c1abf8654'
down_revision = '514546e89a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(length=255), nullable=False, server_default='default_video_path'))
        batch_op.add_column(sa.Column('suggestion', sa.Text(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('suggestion')
        batch_op.drop_column('video')

    # ### end Alembic commands ###
